PIXELSTAR_DATE_YEAR := $(shell date -u +%Y)
PIXELSTAR_DATE_MONTH := $(shell date -u +%m)
PIXELSTAR_DATE_DAY := $(shell date -u +%d)
PIXELSTAR_DATE_HOUR := $(shell date -u +%H)
PIXELSTAR_DATE_MINUTE := $(shell date -u +%M)
PIXELSTAR_BUILD_DATE := $(PIXELSTAR_DATE_YEAR)$(PIXELSTAR_DATE_MONTH)$(PIXELSTAR_DATE_DAY)-$(PIXELSTAR_DATE_HOUR)$(PIXELSTAR_DATE_MINUTE)


PIXELSTAR_BUILDTYPE ?= UNOFFICIAL

PIXELSTAR_DISPLAY_VERSION := 4.0

PIXELSTAR_PLATFORM_VERSION := 15.0
PIXELSTAR_CODENAME := Madhyan

PIXELSTAR_VERSION := ProjectPixelstar-v$(PIXELSTAR_DISPLAY_VERSION)-$(PIXELSTAR_CODENAME)-$(PIXELSTAR_BUILD)-$(PIXELSTAR_PLATFORM_VERSION)-$(PIXELSTAR_BUILDTYPE)-$(PIXELSTAR_BUILD_DATE)

# PIXELSTAR Platform Version
PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
    ro.pixelstar.build.date=$(BUILD_DATE) \
    ro.pixelstar.build.version=$(PIXELSTAR_DISPLAY_VERSION) \
    ro.pixelstar.build.versioncodename=$(PIXELSTAR_CODENAME) \
    ro.pixelstar.device=$(PIXELSTAR_BUILD) \
    ro.pixelstar.fingerprint=$(ROM_FINGERPRINT) \
    ro.pixelstar.releasetype=$(PIXELSTAR_BUILDTYPE) \
    ro.pixelstar.version=$(PIXELSTAR_VERSION) \
    ro.modversion=$(PIXELSTAR_VERSION)
